pipes:
  - name: HighCostQueue
    type: 
    dlq: true 
    persistent: true
  - name: PipeB
    persistent: true

filters:
  - name: ComponentA
    type: ContentBasedRouter
    inputQueues: 
      HighCostQueue:PipeA
    outputQueues:
      - PipeB
      - PipeC
    behavior:
      conditions:
        - condition: "message.type == 'type1'"
          queue: PipeB
        - condition: "message.type == 'type2'"
          queue: PipeC

deployment-hosts:

deployment-environments: 
  - pipes:
      type: rabbitmq
      address: localhost
      http-port: 15672
      amqp-port: 5672
      username: admin
      password: admin
  - filters:
      type: docker-compose