version: '3.7'
services:
  dapr:
    image: daprio/dapr
    volumes:
      - ./components:/components
    command: ["./daprd"]
  ComponentA:
    image: pstopper/cbr:latest
    environment:
      INPUT_QUEUE: PipeA
      OUTPUT_QUEUES: PipeB;PipeC
    depends_on:
      - dapr
