apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-binding
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://admin:admin@localhost:5672"
  - name: durable
    value: "true"
  - name: deletedWhenUnused
    value: "false"
  - name: queue1
    value: "queue-name-1"
  - name: queue2
    value: "queue-name-2"
  - name: queue3
    value: "queue-name-3"