pipes:
  queues:
    - id: 3b76043e-676b-4029-9008-b0215cec8e1d
      name: "JOOOO"
      host: "myRabbitOnK8s"
      protocol: "amqp"
    - id: 3b76043e-676b29-9008-b0215cec8e1d
      name: "testOutputOne"
      host: "myRabbitOnK8s"
      protocol: "amqp"
    - id: 3b76043e-676b-4029-9008-b02cec8e1d
      name: "testOutputTwo"
      host: "myRabbitOnK8s"
      protocol: "amqp"
  topics:
    - id: 3b76043e-676b-4029-9008-b0cec8e1d
      name: "testTopic"
      host: "myRabbitOnK8s"
      protocol: "amqp"

filters:
  - id: 577a26d2-216c-4e6e-95e0-e7808f8394
    name: "testSender"
    host: "myKubernetes"
    type: "amqpSender"
    message: "Blablabla"
    mappings:
      - "outputPipe:JOOOO"
  - id: 577a26d2-216c-4e6e-95e0-e7808f83
    name: "testReceiver"
    host: "myDocker"
    type: "amqpReceiver"
    mappings:
      - "inputPipe:JOOOO"
  - id: 577a26d2-216c-4e6e-95e0-e7808f8
    name: "testRouter"
    host: "myKubernetes"
    type: "ConfigurableRouter"
    routingCriterias: routing_logic.json
    mappings:
      - inputPipe:JOOOO
      - outputPipeOne:testOutputOne
      - outputPipeTwo:testOutputTwo
  - id: 577a26-216c-4e6e-95e0-e7808f8
    name: "testRouter"
    host: "myDocker"
    type: "ConfigurableRouter"
    routingCriterias: routing_logic.json
    mappings:
      - inputPipe:JOOOO
      - outputPipeOne:testOutputOne
      - outputPipeTwo:testOutputTwo
    