services:
  costrouterdc:
    environment:
    - lowCostQueue=myPipe
    - highCostQueue=myCoolMqttPipe
    - inputQueue=productionPipe
    image: pstopper/coolRouter
  myrouterrouter:
    environment:
    - inputPipes=myPipe
    - outputPipes=myPipe
    image: eicoda/configurable-router:latest
version: "3"
