services:
  worldsender:
    environment:
    - out=amqp://admin:password@localhost:5672,messagePipe,queue
    - 'data={"greeting": "Hallo Welt"}'
    - interval=3000
    - eventType=dummy
    image: pstopper/eicoda-sender:latest
    volumes: []
version: "3"
volumes: {}
