services:
  orderprocessor:
    environment:
    - in=amqp://admin:password@localhost:5672,OrderQueue
    image: pstopper/eicoda-receiver:latest
    volumes: []
  webshopbackend:
    environment:
    - internalOrdersPipe=amqp://admin:password@localhost:5672,OrderQueue
    image: pstopper/backend-container:latest
    volumes: []
version: "3"
volumes: {}
