apiVersion: apps/v1
kind: Deployment
metadata:
  name: testsender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testsender
  template:
    metadata:
      labels:
        app: testsender
    spec:
      containers:
      - env:
        - name: outputPipe
          value: amqp://admin:password@localhost:5672
        image: pstopper/eicoda-amqp-sender:latest
        name: testsender
