apiVersion: apps/v1
kind: Deployment
metadata:
  name: testsender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testsender
  template:
    metadata:
      labels:
        app: testsender
    spec:
      containers:
      - env:
        - name: outputPipe
          value: myPipe
        image: pstopper/eicoda-amqp-sender:latest
        name: testsender
---
apiVersion: v1
kind: Service
metadata:
  name: testsender
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: testsender
