apiVersion: apps/v1
kind: Deployment
metadata:
  name: nehrensender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nehrensender
  template:
    metadata:
      labels:
        app: nehrensender
    spec:
      containers:
      - env:
        - name: out
          value: amqp://admin:password@rabbitmq:5672,messagePipe,queue
        - name: data
          value: '{"greeting": "Hallo Reutlingen"}'
        - name: interval
          value: "3000"
        - name: eventType
          value: dummy
        image: pstopper/eicoda-sender:latest
        name: nehrensender
        volumeMounts: []
      volumes: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reutlingenreceiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reutlingenreceiver
  template:
    metadata:
      labels:
        app: reutlingenreceiver
    spec:
      containers:
      - env:
        - name: in
          value: amqp://admin:password@rabbitmq:5672,reutlingenPipe,queue
        image: pstopper/eicoda-receiver:latest
        name: reutlingenreceiver
        volumeMounts: []
      volumes: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldreceiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worldreceiver
  template:
    metadata:
      labels:
        app: worldreceiver
    spec:
      containers:
      - env:
        - name: in
          value: amqp://admin:password@rabbitmq:5672,worldPipe,topic
        image: pstopper/eicoda-receiver:latest
        name: worldreceiver
        volumeMounts: []
      volumes: []
