version: '3.4'
services:
  sender:
    image: eip-sender-py:latest
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - daprd

  daprd:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "-app-id", "sender",
      "-app-port", "5000",
      "-dapr-http-port", "3500",
      "-components-path", "/components"
    ]
    volumes:
      - "./components:/components"
    depends_on:
      - sender
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
