pipes:
  queues:
    - id: 3b76043e-676b-4029-9008-b0215cec
      name: "reutlingenPipe"
      host: "devRabbitMQ"
      protocol: "amqp"
    - id: 3b76043e-676b-4029-9008-b0215cec8e
      name: "messagePipe"
      host: "devRabbitMQ"
      protocol: "amqp"
    - id: 3b76043e-676b-40
      name: "translatedPipe"
      host: "devRabbitMQ"
      protocol: "amqp"
  topics:
    - id: 3b76043e-676b-4029-9008-b0215cec8e1d
      name: "worldPipe"
      host: "devRabbitMQ"
      protocol: "amqp"

filters:
  - id: 577a26d2-216
    name: "worldSender"
    host: "devDockerCompose"
    type: "Sender"
    data: '{"greeting": "Hallo World"}'
    mappings:
      - "out:messagePipe"
  - id: 577a26d2-216c-4e6e-95e0-e7808f8394
    name: "nehrenSender"
    host: "devDockerCompose"
    type: "Sender"
    data: '{"greeting": "Hallo Reutlingen"}'
    mappings:
      - "out:messagePipe"
  - id: 577a26d2-216c-4e6e-95e0-e7
    name: "testRouter"
    host: "devDockerCompose"
    type: "FlexRouter"
    criteria: "criteria.json"
    mode: "single"
    mappings:
      - "in:messagePipe"
      - "outOne:reutlingenPipe"
      - "outTwo:worldPipe->logs.#"
  - id: 577a26d2-216c-4e6e-95e0-e7808f83
    name: "reutlingenReceiver"
    host: "devDockerCompose"
    type: "Receiver"
    mappings:
      - "in:reutlingenPipe"
  - id: 577a26d2-216c-4e6e-9
    name: "worldTranslatedReceiver"
    host: "devDockerCompose"
    type: "Receiver"
    mappings:
      - "in:translatedPipe"
  - id: 577a26d2-216c-4
    name: "testTranslator"
    host: "devDockerCompose"
    type: "Translator"
    criteria: "translation.json"
    mappings:
      - "in:worldPipe"
      - "out:translatedPipe"